create table "user"
(
    id          bigint primary key generated by default as identity,
    name        varchar(40) not null,
    address     varchar(40) not null,
    description varchar(40) not null
);
